version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: appeals_postgres
    environment:
      POSTGRES_USER: admin #оставил для тестового задания без env
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: appeals_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: